### ISSUE TITLE
Hi professor, I have changed the shell scripts for hw1 ex1,ex2

### ISSUE THREAD

**Issue by ZhuWeifeng94** [ZhuWeifeng94/stat679work#2]
https://github.com/ZhuWeifeng94/stat679work/commit/035fdb8a88b6e2e6f3affb4c15919fc17adca72d
@cecileane
Hi professor,
Thank you for all your great suggestions for my hw1 ex1,2 so much!
I have changed my shell scripts for hw1 ex1,ex2 following what you told me and updated them.
Since I have submitted h1 ex3, I named the shell script for hw1 ex2 as summarizeSNaQres_ex2.sh.

Thank you so much again!

Weifeng Zhu

**Comment by cecileane** [comment]
Great! You can simply use this feedback in your exercise 3 (with your new header line and no extra space in the csv file your instance).
